CC = g++
CPPFLAGS = -Wall -g -std=c++11

project5:		vertex.o graph.o vertex.h graph.h 

project5.o:		vertex.h

vertex.o:		graph.h

graph.o:


.PHONY:	clean
clean:			# clean the directory
			$(info -- cleaning the directory --)
			rm -f *.o
			rm -f project5
